; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:PRSLab_FC]
platform = ststm32
; 这里的名字必须和你的 json 文件名一模一样！
board = PRSLab_FC
framework = stm32cube
upload_protocol = cmsis-dap
debug_tool = cmsis-dap