; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; 把这里改成你专属的名字
[env:PRSLab_FC]
platform = ststm32
; 警告：下面这一行绝对不能改！
board = nucleo_h753zi
framework = stm32cube

upload_protocol = cmsis-dap
debug_tool = cmsis-dap